version: "3"

networks: 
    users_microservice_network:
        driver: bridge

services:
    users-microservice-database:
        container_name: users-microservice-database
        image: mysql:latest
        ports:
          - "3306:3306"
        networks:
          - users_microservice_network
        volumes:
          - /data/mysql
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=123456
          - MYSQL_DATABASE=isc517_users

    users-microservice-app:
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - users-microservice-database
        ports:
            - "8080:8080"
        volumes:
            - /data/users-microservice-app
        networks:
            - users_microservice_network
